### ISSUE TITLE
java.lang.IllegalStateException: Surface has already been released

### ISSUE THREAD

**Issue by adeldolgov** [danielzeller/Blur-LIB-Android#11]
This happens when i just go to another activity and then goes back.

**Comment by adeldolgov** [comment]
java.lang.IllegalStateException: Surface has already been released.
        at android.view.Surface.checkNotReleasedLocked(Surface.java:568)
        at android.view.Surface.lockHardwareCanvas(Surface.java:382)
        at no.danielzeller.blurbehindlib.opengl.ViewSurfaceTexture.beginDraw(ViewSurfaceTexture.kt:48)
        at no.danielzeller.blurbehindlib.BlurBehindLayout.renderBehindViewToTexture(BlurBehindLayout.kt:240)
        at no.danielzeller.blurbehindlib.BlurBehindLayout.redrawBlurTexture(BlurBehindLayout.kt:216)
        at no.danielzeller.blurbehindlib.BlurBehindLayout.access$redrawBlurTexture(BlurBehindLayout.kt:25)
        at no.danielzeller.blurbehindlib.BlurBehindLayout$frameCallBack$1.doFrame(BlurBehindLayout.kt:234)

**Comment by adeldolgov** [comment]
1. I have fragment with Google Map
2. Fragment container is setted as blurbehindview 
3. If i scroll map, then go to another activity, then go back, i got that error.

**Comment by fidelisakilan** [comment]
did u fix this issue?

**Comment by grimmthejow** [comment]
looks the developer is too lazy to fix this, ig we're stuck with this forever
