### ISSUE TITLE
Crash after reenter activity

### ISSUE THREAD

**Issue by adeldolgov** [danielzeller/Blur-LIB-Android#8]
I wrote this lines in my onPause and onResume methods.
When i press 'home' button, then go to app again after some minutes, i'm getting this error
I have fragment container that was set as blur behind

```
    @Override
    protected void onPause() {
        super.onPause();
        if(blurBehindLayout!=null)
            blurBehindLayout.disable();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if(blurBehindLayout!=null)
            blurBehindLayout.enable();
    }
```

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@34302ee
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.widget.ImageView.onDraw(ImageView.java:1367)
        at android.view.View.draw(View.java:19196)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19199)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19199)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19199)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18137)
        at android.view.View.draw(View.java:18924)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19199)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18146)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3006)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2810)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2363)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:713)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)

**Comment by danielzeller** [comment]
This crash is not from BlurLib. Blur Lib doesn't use any Bitmaps internally. 
You are trying to use a Recycled bitmap in one of your ImageView within your app.
